version: 2

sources:
  - name: raw
    schema: D17C1
    tables:
      - name: sales
        freshness:
          warn_after: {count: 90, period: day}
          error_after:
            period: day
            count: 4500
        loaded_at_field: CAST(date_date AS TIMESTAMP)
        identifier: raw_gz_sales
        description: Sales of Greenweez
        columns:
          - name: orders_id
            description: Order ID
          - name: pdt_id
            description: Product ID
          - name: date_date
            description: TBD
          - name: revenue
            description: TBD
          - name: quantity
            description: TBD
      - name: product
        identifier: raw_gz_product
        description: Product catalog of Greenweez
        columns:
          - name: products_id
            description: Product ID
            tests:
              - unique
              - not_null                  
          - name: purchSE_PRICE
            description: TBD
      - name: ship
        identifier: raw_gz_ship
        description: Table of shipping data of Greenweez
        columns:
          - name: orders_id,
            description: Order ID
          - name: shipping_fee
            description: TBD
          - name: shipping_fee_1
            description: TBD
          - name: logCost
            description: TBD
          - name: ship_cost
            description: TBD
      - name: adwords
        identifier: raw_gz_adwords
        description: Table of data from adwords
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: bing
        identifier: raw_gz_bing
        description: Table of data from bing
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: criteo
        identifier: raw_gz_criteo
        description: Table of data from criteo
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: facebook
        identifier: raw_gz_facebook
        description: Table of data from facebook
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click